bhv_teleop:
  ####tele-op, ang in degrees####
  ##left up/down controls surge
  ##X and B controls yaw
  ##Y and A controls pitch
  ##RB and RT controls depth
  ## LB has to be pressed 
  ##LT resets desired states to zero for all.
  tele_s_surge: 2.0
  tele_s_sway: 1.0
  tele_d_yaw: 10.0 
  tele_d_pitch: 10.0
  tele_d_depth: 0.5


