control_modes:
  idle: false

  teleop:
    z:        {p: 20.0,    i: 2.0 ,  d: 5.0,  i_max: 30, i_min: -30}
    u:        {p: 50.0,    i: 10.0,   d: 0.0,   i_max: 30, i_min: -30}
    pitch:    {p: 30.0,   i: 0.5,  d: 1.0,  i_max: 20, i_min: -20}
    yaw:      {p: 10.0,   i: 0.2,   d: 5.0,  i_max: 20, i_min: -20}

  flight:
    # z:        {p: 20.0,    i: 2.0 ,  d: 5.0,  i_max: 30, i_min: -30}
    u:    {p: 50.0,    i: 10.0,   d: 0.0,   i_max: 30, i_min: -30}
    # pitch:    {p: 10.0,    i: 0.0,   d: 10.0,  i_max: 20, i_min: -20}
    # yaw:      {p: 10.0,    i: 1.0,   d: 10.0,  i_max: 30, i_min: -30}

  4dof:
    z:        {p: 10.0,   i: 1.0 ,  d: 5.0,  i_max: 20, i_min: -20}
    u:        {p: 50.0,    i: 10.0,   d: 0.0,   i_max: 30, i_min: -30}
    pitch:    {p: 30.0,   i: 0.5,  d: 1.0,  i_max: 20, i_min: -20}
    yaw:      {p: 10.0,   i: 0.2,   d: 5.0,  i_max: 20, i_min: -20}

thruster_ids:
  sway_stern:
    control_tf: sway_stern_thruster_link
    command_topic: control/thruster/sway_stern
    force_topic: control/force/sway_stern
    limits: [-20.0, 20.0]] #[min, max]
    polynomials: [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]

  heave_bow:
    control_tf: heave_bow_thruster_link
    command_topic: control/thruster/heave_bow
    force_topic: control/force/heave_bow
    limits: [-20.0, 20.0]] #[min, max]
    polynomials: [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]

  heave_stern_port:
      control_tf: heave_stern_port_thruster_link
      command_topic: control/thruster/heave_stern_port
      force_topic: control/force/heave_stern_port
      limits: [-20.0, 20.0] #[min, max]
      polynomials: [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]

  heave_stern_stbd:
    control_tf: heave_stern_stbd_thruster_link
    command_topic: control/thruster/heave_stern_stbd
    force_topic: control/force/heave_stern_stbd
    limits: [-20.0, 20.0] #[min, max]
    polynomials: [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]

  surge_port:
    control_tf: surge_port_thruster_link
    command_topic: control/thruster/surge_port
    force_topic: control/force/surge_port
    limits: [-20.0, 20.0] #[min, max]
    polynomials: [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]

  surge_stbd:
    control_tf: surge_stbd_thruster_link
    command_topic: control/thruster/surge_stbd
    force_topic: control/force/surge_stbd
    limits: [-20.0, 20.0] #[min, max]
    polynomials: [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]
