generator_type: tf

# controller_frequency: 20
controller_frequency: 20

# tf_prefix: alpha_rise
cg_link: cg_link

odometry_source: /odometry/filtered/local

enabled: false

control_modes:
  idle: false

  teleop:
    surge:      {p: 1.0,  i: 3.0,   d: 5.0,  i_max: 10, i_min: -10}
    yaw_rate:   {p: 2.0,  i: 0.5,   d: 3.0,  i_max: 20, i_min: -20}
    pitch_rate: {p: 2.0,  i: 0.5,   d: 3.0,  i_max: 20, i_min: -20}

  flight:
    z:        {p: 20.0,    i: 2.0 ,  d: 5.0,  i_max: 30, i_min: -30}
    surge:    {p: 50.0,    i: 10.0,   d: 0.0,   i_max: 30, i_min: -30}
    pitch:    {p: 10.0,    i: 0.0,   d: 10.0,  i_max: 20, i_min: -20}
    yaw:      {p: 10.0,    i: 1.0,   d: 10.0,  i_max: 30, i_min: -30}

  hold_xyz:
    x:        {p: 2.5,    i: 1.0,   d: 5.0,  i_max: 10, i_min: -10}
    y:        {p: 2.5,    i: 1.0 ,  d: 5.0,  i_max: 10, i_min: -10}
    z:        {p: 10.0,   i: 0.1 ,  d: 20.0, i_max: 20, i_min: -20}

  hold_depth:
    # z:        {p: 5.0,   i: 0.3 ,  d: 15.0, i_max: 20, i_min: -20}
    # pitch:    {p: 5.0,    i: 1.0,   d: 5.0,  i_max: 20, i_min: -20}
    yaw:      {p: 5.0,    i: 1.0,   d: 10.0,  i_max: 30, i_min: -30}

  hold_4dof:
    x:        {p: 2.5,    i: 1.0,   d: 5.0,  i_max: 10, i_min: -10}
    y:        {p: 2.5,    i: 1.0 ,  d: 5.0,  i_max: 10, i_min: -10}
    z:        {p: 10.0,   i: 1.0 ,  d: 5.0,  i_max: 20, i_min: -20}
    pitch:    {p: 10.0,   i: 0.01,  d: 5.0,  i_max: 20, i_min: -20}

  hold_5dof:
    # x:        {p: 2.5,    i: 1.0,   d: 5.0,  i_max: 10, i_min: -10}
    # y:        {p: 2.5,    i: 1.0 ,  d: 5.0,  i_max: 10, i_min: -10}
    # z:        {p: 10.0,   i: 1.0 ,  d: 5.0,  i_max: 20, i_min: -20}
    # surge:    {p: 50.0,    i: 10.0,   d: 0.0,   i_max: 30, i_min: -30}
    # heave:    {p: 10.0,   i: 1.0,  d: 5.0,  i_max: 20, i_min: -30}
    # yaw_rate: {p: 2.0,  i: 0.5,   d: 3.0,  i_max: 20, i_min: -20}
    # pitch_rate: {p: 2.0,  i: 0.5,   d: 3.0,  i_max: 20, i_min: -20}
    pitch:    {p: 10.0,   i: 0.1,  d: 5.0,  i_max: 20, i_min: -20}
    yaw:      {p: 10.0,   i: 0.2,   d: 5.0,  i_max: 20, i_min: -20}




##
# THRUSTERS
##
thruster_ids:
  - surge
  - sway_bow
  - heave_bow
  - heave_stern

control_tf:
  surge: surge_thruster_link
  sway_bow: sway_bow_thruster_link
  heave_bow: heave_bow_thruster_link
  heave_stern: heave_stern_thruster_link

thruster_command_topics:
  surge: control/thruster/surge
  sway_bow: control/thruster/sway_bow
  heave_bow: control/thruster/heave_bow
  heave_stern: control/thruster/heave_stern

thruster_force_topics:
  surge: control/force/surge
  sway_bow: control/force/sway_bow
  heave_bow: control/force/heave_bow
  heave_stern: control/force/heave_stern


##
# Polynomials for each thruster.
#
# Quadratic Programming Optimization computes the thrust
# required. We need to turn that number into thruster command.
# Setpoint commands in this system defined between -1 and 1.
#
# y axis of the polynomial , f(x) = y, should be in Newton.
#
# Take the polynomial
# f(x) = a_n x^n + a_(n-1) x^(n-1) + ... + a_1 x + a_0
#
# Array would hold the lower degrees in lower indexes. Shown below:
# [a_0, a_1, ... ,a_(n-1), a(n)]
#   f(x) = a5*x^5 + a4*x^4 + a3*x^3 + a2*x^2 + a1*x + a0
#
# For T200 bluerobotics thrusters:
# Curve fitting results:
#   a0 =      0.06165
#   a1 =      20.32
#   a2 =      9.632
#   a3 =      93.05
#   a4 =      -2.856
#   a5 =      -74.1
#
# For T500 bluerobotics thrusters:
# Curve fitting results:
#   a0 =      -0.03703
#   a1 =      4.217
#   a2 =      2.84
#   a3 =      4.976
#   a4 =      -0.4119
#   a5 =      -0.8448
#
##
thruster_polynomials:
  # surge:        [0.5038, 31.49, 29.78, 139.5, -18.66, -113.1]
  # sway_bow:     [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]
  # heave_bow:    [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]
  # heave_stern:  [0.06165, 20.32, 9.632, 93.05, -2.856, -74.1]
  surge:        [0.3281, 44.1281, 22.8029, 84.2361, -6.5710, -41.5185]
  sway_bow:     [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]
  heave_bow:    [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]
  heave_stern:  [0.0305, 18.9527, 6.1205, 64.0375, 2.4386, -24.8871]
  
## Force limits
## T200 limit is +-25 N beyond that will cause nan solution in QP

thruster_limits:
  surge:
    max: 60
    min: -10
  sway_bow:
    max: 25
    min: -25
  heave_bow:
    max: 25
    min: -25
  heave_stern:
    max: 25
    min: -25