Serial:
  port: /dev/ttyACM0
  baud: 115200
  parity: 0
  databits: 8
  stopbits: 1
  timeout: 1000

System:
  safety_timeout: 3
  safety_rate: 1

PWM_Control:
  heave_bow:
    channel: 0
    mode: thruster
    topic: control/thruster/HeaveBow
  surge_port:
    channel: 1
    mode: thruster
    topic: control/thruster/SurgePort
  sway_stern:
    channel: 2
    mode: thruster
    topic: control/thruster/SwayStern
  surge_stdb:
    channel: 3
    mode: thruster
    topic: control/thruster/SurgeStbd 
  heave_port:
    channel: 4
    mode: thruster
    topic: control/thruster/HeaveSternPort
  heave_stdb:
    channel: 5
    mode: thruster
    topic: control/thruster/HeaveSternStbd
  