Serial:
  port: /dev/ttyACM0
  baud: 115200
  parity: 0
  databits: 8
  stopbits: 1
  timeout: 1000

System:
  safety_timeout: 3
  safety_rate: 1

PWM_Control:
  heave_bow:
    channel: 0
    mode: thruster
    topic: control/thruster/heave_bow
  surge_port:
    channel: 1
    mode: thruster
    topic: control/thruster/surge_port
  sway_stern:
    channel: 2
    mode: thruster
    topic: control/thruster/sway_stern
  surge_stdb:
    channel: 3
    mode: thruster
    topic: control/thruster/surge_stdb
  heave_port:
    channel: 4
    mode: thruster
    topic: control/thruster/heave_port
  heave_stdb:
    channel: 5
    mode: thruster
    topic: control/thruster/heave_stdb
  